version: '3.8'

services:
  api:
    restart: always
    ports:
      - 8081:8081
    build:
      context: ./server
      dockerfile: ./Dockerfile
    command: npm run dev
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    networks:
      - local

  frontend:
    restart: always
    ports:
      - 3000:3000
    build:
      context: ./client
      dockerfile: ./Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - ./client/.env
    depends_on:
      - api
    networks:
      - local

  mongo:
    image: mongo
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - apiDB:/data/db
    networks:
      - local

volumes:
  apiDB:

networks:
  local:
