version: '2.2'

services:
  api:
    restart: always
    expose:
      - 8081
    ports:
      - 8081:8081
    build:
      context: ./server
      dockerfile: ./Dockerfile
    volumes:
      - ./server:/app
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - local

  frontend:
    restart: on-failure
    expose:
      - 8080
    ports:
      - 8080:8080
    build:
      context: ./client
      dockerfile: ./Dockerfile
    command: npm run dev
    volumes:
      - ./client:/app
      - ./node_modules:/app/node_modules
    env_file:
      - .env
    depends_on:
      - api
    networks:
      - local

  admin:
    restart: on-failure
    expose:
      - 3000
    ports:
      - 3000:3000
    build:
      context: ./admin
      dockerfile: ./Dockerfile
    command: npm run dev
    volumes:
      - ./admin:/app
      - ./node_modules:/app/node_modules
    env_file:
      - .env
    depends_on:
      - api
    networks:
      - local

  mongo:
    image: mongo
    restart: on-failure
    volumes:
      - apiDB:/data/db
    networks:
      - local

volumes:
  apiDB:

networks:
  local:
