version: '3.8'

services:
  api:
    restart: on-failure
    ports:
      - 8081:8081
    build:
      context: ./server
      dockerfile: ./Dockerfile
    command: npm run dev
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    networks:
      - local

  frontend:
    restart: on-failure
    expose:
      - 80
    ports:
      - 80:80
    build:
      context: ./client
      dockerfile: ./Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - ./client/.env
    depends_on:
      - api
    networks:
      - local

  admin:
    restart: on-failure
    expose:
      - 3000
    ports:
      - 3000:3000
    build:
      context: ./admin
      dockerfile: ./Dockerfile
    volumes:
      - ./admin:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - ./admin/.env
    depends_on:
      - api
    networks:
      - local

  mongo:
    image: mongo
    restart: on-failure
    volumes:
      - apiDB:/data/db
    networks:
      - local

volumes:
  apiDB:

networks:
  local:
