version: '2.2'

services:
  frontend:
    expose:
      - 80
    ports:
      - 80:80
    command: npm run production

  admin:
    expose:
      - 4000
    ports:
      - 4000:4000
    command: npm run production